- type: job
  id: TechnicalAssistant
  name: job-name-technical-assistant
  description: job-description-technical-assistant
  playTimeTracker: JobTechnicalAssistant
  startingGear: TechnicalAssistantGear
  icon: "JobIconTechnicalAssistant"
  supervisors: job-supervisors-engineering
  access:
  - Maintenance
  - Engineering
  - External
  requirements:
  - !type:CharacterEmployerRequirement
    employers:
    - HephaestusIndustries
    - ZavodskoiInterstellar
    - EinsteinEngines
    - NanoTrasen

- type: startingGear
  id: TechnicalAssistantGear
  subGear:
  - StationEngineerPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorYellow
    back: ClothingBackpackEngineering
    shoes: ClothingShoesBootsWork
    id: TechnicalAssistantPDA
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
    pocket2: BookEngineersHandbook
<<<<<<< HEAD
=======
    innerClothingSkirt: ClothingUniformJumpskirtColorYellow
    satchel: ClothingBackpackSatchelEngineeringFilled
    duffelbag: ClothingBackpackDuffelEngineeringFilled
>>>>>>> 9ab8822c4f9158ac83aa446d592e48410d646f06
