- type: job
  id: Psychologist
  name: job-name-psychologist
  description: job-description-psychologist
  playTimeTracker: JobPsychologist
  startingGear: PsychologistGear
  icon: "JobIconPsychologist"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  - Psychologist
  extendedAccess:
  - Chemistry
  requirements:
  - !type:CharacterEmployerRequirement
    employers:
    - Interdyne
    - NanoTrasen

- type: startingGear
  id: PsychologistGear
  subGear:
  - PsychologistPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPsychologist
    back: ClothingBackpackMedical
    shoes: ClothingShoesLeather
    id: PsychologistPDA
    ears: ClothingHeadsetMedical
<<<<<<< HEAD
  storage:
    back:
    - RubberStampPsychologist
=======
    innerClothingSkirt: ClothingUniformJumpsuitPsychologist
    satchel: ClothingBackpackSatchelPsychologistFilled #DeltaV - stamp included
    duffelbag: ClothingBackpackDuffelPsychologistFilled #DeltaV - stamp included
>>>>>>> 9ab8822c4f9158ac83aa446d592e48410d646f06

- type: startingGear
  id: PsychologistPlasmamanGear
  parent: BasePlasmamanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitEnviroslacksPsychologist
    head: ClothingHeadEnvirohelmMedicalDoctor
    gloves: ClothingHandsGlovesEnviroglovesWhite
