- type: job
  id: Reporter
  name: job-name-reporter
  description: job-description-reporter
  playTimeTracker: JobReporter
  startingGear: ReporterGear
  icon: "JobIconReporter"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - Theatre
  - Reporter
  requirements:
  - !type:CharacterEmployerRequirement
    inverted: true
    employers:
    - Unemployed

- type: startingGear
  id: ReporterGear
  subGear:
  - ReporterPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitReporter
    back: ClothingBackpack
    shoes: ClothingShoesColorWhite
    id: ReporterPDA
    ears: ClothingHeadsetService
<<<<<<< HEAD
=======
    innerClothingSkirt: ClothingUniformJumpsuitJournalist
    satchel: ClothingBackpackSatchelFilled
    duffelbag: ClothingBackpackDuffelFilled
>>>>>>> 9ab8822c4f9158ac83aa446d592e48410d646f06

- type: startingGear
  id: ReporterPlasmamanGear
  parent: BasePlasmamanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitReporter
    head: ClothingHeadEnvirohelmReporter
    gloves: ClothingHandsGlovesEnviroglovesReporter
