- type: startingGear
  id: CourierGear
  subGear:
  - CourierPlasmamanGear
  equipment:
    head: ClothingHeadCourier
    jumpsuit: ClothingUniformCourier
    back: ClothingBackpack
    shoes: ClothingShoesColorBlack
    id: MailCarrierPDA
    ears: ClothingHeadsetCargo
    belt: CourierBag
<<<<<<< HEAD
=======
    innerClothingSkirt: ClothingUniformSkirtCourier
    satchel: ClothingBackpackSatchelFilled
    duffelbag: ClothingBackpackDuffelFilled
>>>>>>> 9ab8822c4f9158ac83aa446d592e48410d646f06

- type: startingGear
  id: CourierPlasmamanGear
  parent: BasePlasmamanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitCourier
    head: ClothingHeadEnvirohelmCourier
    gloves: ClothingHandsGlovesEnviroglovesCargo
