- type: job
  id: Botanist
  name: job-name-botanist
  description: job-description-botanist
  playTimeTracker: JobBotanist
  startingGear: BotanistGear
  icon: "JobIconBotanist"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - Hydroponics
  extendedAccess:
  - Kitchen
  - Bar
  requirements:
  - !type:CharacterEmployerRequirement
    employers:
    - NanoTrasen
    - ZengHuPharmaceuticals
    - EastOrionCompany

- type: startingGear
  id: BotanistGear
  subGear:
  - BotanistPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHydroponics
    back: ClothingBackpackHydroponics
    shoes: ClothingShoesColorBrown
    id: BotanistPDA
    ears: ClothingHeadsetService
    outerClothing: ClothingOuterApronBotanist
    belt: ClothingBeltPlantFilled
<<<<<<< HEAD
=======
    innerClothingSkirt: ClothingUniformJumpskirtHydroponics
    satchel: ClothingBackpackSatchelHydroponicsFilled
    duffelbag: ClothingBackpackDuffelHydroponicsFilled
>>>>>>> 9ab8822c4f9158ac83aa446d592e48410d646f06

- type: startingGear
  id: BotanistPlasmamanGear
  parent: BasePlasmamanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitHydroponics
    head: ClothingHeadEnvirohelmHydroponics
    gloves: ClothingHandsGlovesEnviroglovesLeather
