- type: job
  id: ServiceWorker
  name: job-name-serviceworker
  description: job-description-serviceworker
  playTimeTracker: JobServiceWorker
  startingGear: ServiceWorkerGear
  icon: "JobIconServiceWorker"
  supervisors: job-supervisors-service
  access:
  - Service
  - Maintenance
  extendedAccess:
  - Hydroponics
  - Bar
  - Kitchen
  requirements:
  - !type:CharacterEmployerRequirement
    inverted: true
    employers:
    - Unemployed

- type: startingGear
  id: ServiceWorkerGear
  subGear:
  - ServiceWorkerPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorDarkGreen
    back: ClothingBackpack
    shoes: ClothingShoesColorBlack
    id: ServiceWorkerPDA
    ears: ClothingHeadsetService
<<<<<<< HEAD
=======
    innerClothingSkirt: ClothingUniformJumpskirtColorDarkGreen # DeltaV
    satchel: ClothingBackpackSatchelFilled
    duffelbag: ClothingBackpackDuffelFilled
>>>>>>> 9ab8822c4f9158ac83aa446d592e48410d646f06

- type: startingGear
  id: ServiceWorkerPlasmamanGear
  parent: BasePlasmamanMaskGear
  equipment:
    jumpsuit: ClothingUniformEnvirosuitColorDarkGreen
    head: ClothingHeadEnvirohelmColorDarkGreen
    gloves: ClothingHandsGlovesEnviroglovesColorDarkGreen
