- type: job
  id: ResearchAssistant
  name: job-name-research-assistant
  description: job-description-research-assistant
  playTimeTracker: JobResearchAssistant
  requirements:
    - !type:CharacterEmployerRequirement
      employers:
      - NanoTrasen
      - ZengHuPharmaceuticals
  startingGear: ResearchAssistantGear
  icon: "JobIconResearchAssistant"
  supervisors: job-supervisors-science
  access:
  - Research
  - Maintenance

- type: startingGear
  id: ResearchAssistantGear
  subGear:
  - ScientistPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorWhite
    back: ClothingBackpackScience
    shoes: ClothingShoesColorWhite
    id: ResearchAssistantPDA
    ears: ClothingHeadsetScience
    pocket1: BookPsionicsGuidebook
    pocket2: BookScientistsGuidebook
<<<<<<< HEAD
  storage:
    back:
    - BoxSurvival
=======
    innerClothingSkirt: ClothingUniformJumpskirtColorWhite
    satchel: ClothingBackpackSatchelScienceFilled
    duffelbag: ClothingBackpackDuffelScienceFilled
>>>>>>> 9ab8822c4f9158ac83aa446d592e48410d646f06
